package com.undergrowth.test.entity;

import java.util.Date;

public class GsmsContact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.id
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.name
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.phone
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.sex
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.identifier
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private String identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.birthday
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.birth_month
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private Integer birthMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.birth_day
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private Integer birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.vip
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private Boolean vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.remark
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.extension1
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private String extension1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.extension2
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private String extension2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.extension3
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private String extension3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gsms_contact.group_id
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.id
     *
     * @return the value of gsms_contact.id
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.id
     *
     * @param id the value for gsms_contact.id
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.name
     *
     * @return the value of gsms_contact.name
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.name
     *
     * @param name the value for gsms_contact.name
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.phone
     *
     * @return the value of gsms_contact.phone
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.phone
     *
     * @param phone the value for gsms_contact.phone
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.sex
     *
     * @return the value of gsms_contact.sex
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.sex
     *
     * @param sex the value for gsms_contact.sex
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.identifier
     *
     * @return the value of gsms_contact.identifier
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.identifier
     *
     * @param identifier the value for gsms_contact.identifier
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.birthday
     *
     * @return the value of gsms_contact.birthday
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.birthday
     *
     * @param birthday the value for gsms_contact.birthday
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.birth_month
     *
     * @return the value of gsms_contact.birth_month
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public Integer getBirthMonth() {
        return birthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.birth_month
     *
     * @param birthMonth the value for gsms_contact.birth_month
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setBirthMonth(Integer birthMonth) {
        this.birthMonth = birthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.birth_day
     *
     * @return the value of gsms_contact.birth_day
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public Integer getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.birth_day
     *
     * @param birthDay the value for gsms_contact.birth_day
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setBirthDay(Integer birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.vip
     *
     * @return the value of gsms_contact.vip
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public Boolean getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.vip
     *
     * @param vip the value for gsms_contact.vip
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setVip(Boolean vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.remark
     *
     * @return the value of gsms_contact.remark
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.remark
     *
     * @param remark the value for gsms_contact.remark
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.extension1
     *
     * @return the value of gsms_contact.extension1
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public String getExtension1() {
        return extension1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.extension1
     *
     * @param extension1 the value for gsms_contact.extension1
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setExtension1(String extension1) {
        this.extension1 = extension1 == null ? null : extension1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.extension2
     *
     * @return the value of gsms_contact.extension2
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public String getExtension2() {
        return extension2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.extension2
     *
     * @param extension2 the value for gsms_contact.extension2
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setExtension2(String extension2) {
        this.extension2 = extension2 == null ? null : extension2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.extension3
     *
     * @return the value of gsms_contact.extension3
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public String getExtension3() {
        return extension3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.extension3
     *
     * @param extension3 the value for gsms_contact.extension3
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setExtension3(String extension3) {
        this.extension3 = extension3 == null ? null : extension3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gsms_contact.group_id
     *
     * @return the value of gsms_contact.group_id
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gsms_contact.group_id
     *
     * @param groupId the value for gsms_contact.group_id
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}