package com.undergrowth.test.mapper;

import com.undergrowth.test.entity.GsmsContact;

public interface GsmsContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gsms_contact
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gsms_contact
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    int insert(GsmsContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gsms_contact
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    int insertSelective(GsmsContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gsms_contact
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    GsmsContact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gsms_contact
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(GsmsContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gsms_contact
     *
     * @mbggenerated Wed Nov 04 15:15:10 GMT+08:00 2015
     */
    int updateByPrimaryKey(GsmsContact record);
}